<?php

// Data functions (insert, update, delete, form) for table orders

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function orders_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('orders');
	if(!$arrPerm[1]){
		return false;
	}
    $data['product'] = makeSafe($_REQUEST['product']);
        if($data['product'] == empty_lookup_value){ $data['product'] = ''; }
    $data['client'] = makeSafe($_REQUEST['client']);
        if($data['client'] == empty_lookup_value){ $data['client'] = ''; }
    $data['mobile'] = makeSafe($_REQUEST['mobile']);
        if($data['mobile'] == empty_lookup_value){ $data['mobile'] = ''; }
     $data['brand'] = makeSafe($_REQUEST['brand']);
        if($data['brand'] == empty_lookup_value){ $data['brand'] = ''; }
     $data['quantity'] = makeSafe($_REQUEST['quantity']);
        if($data['quantity'] == empty_lookup_value){ $data['quantity'] = ''; }
     $data['amount'] = makeSafe($_REQUEST['amount']);
        if($data['amount'] == empty_lookup_value){ $data['amount'] = ''; }
     $data['price'] = makeSafe($_REQUEST['price']);
        if($data['price'] == empty_lookup_value){ $data['price'] = ''; }
     $data['town'] = makeSafe($_REQUEST['town']);
        if($data['town'] == empty_lookup_value){ $data['town'] = ''; }
     $data['estate'] = makeSafe($_REQUEST['estate']);
        if($data['estate'] == empty_lookup_value){ $data['estate'] = ''; }
     $data['point'] = makeSafe($_REQUEST['point']);
        if($data['point'] == empty_lookup_value){ $data['point'] = ''; }
     $data['status'] = makeSafe($_REQUEST['status']);
        if($data['status'] == empty_lookup_value){ $data['status'] = ''; }
    
    if($data['product']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Product': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['client']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Client': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['mobile']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Mobile': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['brand']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Brand': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['quantity']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Quantity': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['amount']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Amount': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['price']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Price': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
	if($data['town']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Town': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['estate']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Estate': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['point']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Pickup point': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
    if($data['status']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Status': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from orders where id='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			
		}
	}
	// hook: orders_before_insert
	if(function_exists('orders_before_insert')){
		$args=array();
		if(!orders_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `orders` set       `town`=' . (($data['town'] !== '' && $data['town'] !== NULL) ? "'{$data['town']}'" : 'NULL') . ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL') . ', `estate`=' . (($data['estate'] !== '' && $data['estate'] !== NULL) ? "'{$data['estate']}'" : 'NULL') . ', `product`=' . (($data['product'] !== '' && $data['product'] !== NULL) ? "'{$data['product']}'" : 'NULL') . ', `client`=' . (($data['client'] !== '' && $data['client'] !== NULL) ? "'{$data['client']}'" : 'NULL') . ', `mobile`=' . (($data['mobile'] !== '' && $data['mobile'] !== NULL) ? "'{$data['mobile']}'" : 'NULL') . ', `brand`=' . (($data['brand'] !== '' && $data['brand'] !== NULL) ? "'{$data['brand']}'" : 'NULL') . ', `quantity`=' . (($data['quantity'] !== '' && $data['quantity'] !== NULL) ? "'{$data['quantity']}'" : 'NULL') . ', `amount`=' . (($data['amount'] !== '' && $data['amount'] !== NULL) ? "'{$data['amount']}'" : 'NULL') . ', `price`=' . (($data['price'] !== '' && $data['price'] !== NULL) ? "'{$data['price']}'" : 'NULL') . ', `point`=' . (($data['point'] !== '' && $data['point'] !== NULL) ? "'{$data['point']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"orders_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: orders_after_insert
	if(function_exists('orders_after_insert')){
		$res = sql("select * from `orders` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!orders_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('orders', $recID, getLoggedMemberID());

	return $recID;
}

function orders_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('orders');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='orders' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='orders' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: orders_before_delete
	if(function_exists('orders_before_delete')){
		$args=array();
		if(!orders_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	
	sql("delete from `orders` where `id`='$selected_id'", $eo);

	// hook: orders_after_delete
	if(function_exists('orders_after_delete')){
		$args=array();
		orders_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='orders' and pkValue='$selected_id'", $eo);
}

function orders_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('orders');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='orders' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='orders' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}
    $data['product'] = makeSafe($_REQUEST['product']);
        if($data['product'] == empty_lookup_value){ $data['product'] = ''; }
    $data['client'] = makeSafe($_REQUEST['client']);
        if($data['client'] == empty_lookup_value){ $data['client'] = ''; }
    $data['mobile'] = makeSafe($_REQUEST['mobile']);
        if($data['mobile'] == empty_lookup_value){ $data['mobile'] = ''; }
     $data['brand'] = makeSafe($_REQUEST['brand']);
        if($data['brand'] == empty_lookup_value){ $data['brand'] = ''; }
     $data['quantity'] = makeSafe($_REQUEST['quantity']);
        if($data['quantity'] == empty_lookup_value){ $data['quantity'] = ''; }
     $data['amount'] = makeSafe($_REQUEST['amount']);
        if($data['amount'] == empty_lookup_value){ $data['amount'] = ''; }
     $data['price'] = makeSafe($_REQUEST['price']);
        if($data['price'] == empty_lookup_value){ $data['price'] = ''; }
     $data['town'] = makeSafe($_REQUEST['town']);
        if($data['town'] == empty_lookup_value){ $data['town'] = ''; }
     $data['estate'] = makeSafe($_REQUEST['estate']);
        if($data['estate'] == empty_lookup_value){ $data['estate'] = ''; }
     $data['point'] = makeSafe($_REQUEST['point']);
        if($data['point'] == empty_lookup_value){ $data['point'] = ''; }
     $data['status'] = makeSafe($_REQUEST['status']);
        if($data['status'] == empty_lookup_value){ $data['status'] = ''; }
    
    if($data['product']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Product': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['client']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Client': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['mobile']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Mobile': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['brand']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Brand': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['quantity']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Quantity': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['amount']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Amount': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['price']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Price': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
	if($data['town']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Town': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['estate']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Estate': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
    if($data['point']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Pickup point': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
    if($data['status']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Status': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
    }
	$data['selectedID']=makeSafe($selected_id);

	// hook: orders_before_update
	if(function_exists('orders_before_update')){
		$args=array();
		if(!orders_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `orders` set       `town`=' . (($data['town'] !== '' && $data['town'] !== NULL) ? "'{$data['town']}'" : 'NULL') . ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL') . ', `estate`=' . (($data['estate'] !== '' && $data['estate'] !== NULL) ? "'{$data['estate']}'" : 'NULL') . ', `product`=' . (($data['product'] !== '' && $data['product'] !== NULL) ? "'{$data['product']}'" : 'NULL') . ', `client`=' . (($data['client'] !== '' && $data['client'] !== NULL) ? "'{$data['client']}'" : 'NULL') . ', `mobile`=' . (($data['mobile'] !== '' && $data['mobile'] !== NULL) ? "'{$data['mobile']}'" : 'NULL') . ', `brand`=' . (($data['brand'] !== '' && $data['brand'] !== NULL) ? "'{$data['brand']}'" : 'NULL') . ', `quantity`=' . (($data['quantity'] !== '' && $data['quantity'] !== NULL) ? "'{$data['quantity']}'" : 'NULL') . ', `amount`=' . (($data['amount'] !== '' && $data['amount'] !== NULL) ? "'{$data['amount']}'" : 'NULL') . ', `price`=' . (($data['price'] !== '' && $data['price'] !== NULL) ? "'{$data['price']}'" : 'NULL') . ', `point`=' . (($data['point'] !== '' && $data['point'] !== NULL) ? "'{$data['point']}'" : 'NULL'). " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="orders_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: orders_after_update
	if(function_exists('orders_after_update')){
		$res = sql("SELECT * FROM `orders` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!orders_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='orders' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function orders_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('orders');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='orders' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='orders' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `orders` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'orders_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_status->SelectedData = $row['status'];
	}else{
		$combo_status->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");

	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/orders_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/orders_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Orders details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return orders_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return orders_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return orders_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ico').replaceWith('<div class=\"form-control-static\" id=\"ico\">' + (jQuery('#ico').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (jQuery('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(product)%%>', safe_html($urow['product']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(product)%%>', html_attr($row['product']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(product)%%>', urlencode($urow['product']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', safe_html($urow['client']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(client)%%>', html_attr($row['client']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode($urow['client']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(mobile)%%>', safe_html($urow['mobile']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mobile)%%>', html_attr($row['mobile']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(mobile)%%>', urlencode($urow['mobile']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(brand)%%>', safe_html($urow['brand']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(brand)%%>', html_attr($row['brand']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(brand)%%>', urlencode($urow['brand']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(quantity)%%>', safe_html($urow['quantity']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(quantity)%%>', html_attr($row['quantity']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(quantity)%%>', urlencode($urow['quantity']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(amount)%%>', safe_html($urow['amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(amount)%%>', html_attr($row['amount']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(amount)%%>', urlencode($urow['amount']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(price)%%>', safe_html($urow['price']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(price)%%>', html_attr($row['price']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(price)%%>', urlencode($urow['price']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(town)%%>', safe_html($urow['town']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(town)%%>', html_attr($row['town']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(estate)%%>', urlencode($urow['estate']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(estate)%%>', safe_html($urow['estate']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estate)%%>', html_attr($row['estate']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(estate)%%>', urlencode($urow['estate']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(point)%%>', safe_html($urow['point']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(point)%%>', html_attr($row['point']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(point)%%>', urlencode($urow['point']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['point']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['point']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['point']), $templateCode);
        
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(product)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(product)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(client)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(client)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(mobile)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(mobile)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(brand)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(brand)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(quantity)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(quantity)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(amount)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(amount)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(price)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(price)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(town)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(town)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(estate)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(estate)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(point)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(point)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
	}
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('orders');
	if($selected_id){
		$jdata = get_joined_record('orders', $selected_id);
		if($jdata === false) $jdata = get_defaults('orders');
		$rdata = $row;
	}
	$templateCode .= loadView('orders-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: orders_dv
	if(function_exists('orders_dv')){
		$args=array();
		orders_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>