<?php

// Data functions (insert, update, delete, form) for table products

// This script and data application were generated by AppGini 5.72
// Download AppGini for free from https://bigprof.com/appgini/download/

function products_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('products');
	if(!$arrPerm[1]){
		return false;
	}
    $data['cost'] = makeSafe($_REQUEST['cost']);
        if($data['cost'] == empty_lookup_value){ $data['cost'] = ''; }
    $data['weight'] = makeSafe($_REQUEST['weight']);
        if($data['weight'] == empty_lookup_value){ $data['weight'] = ''; }
    $data['quantity'] = makeSafe($_REQUEST['quantity']);
        if($data['quantity'] == empty_lookup_value){ $data['quantity'] = ''; }
    $data['category'] = makeSafe($_REQUEST['category']);
        if($data['category'] == empty_lookup_value){ $data['category'] = ''; }
    $data['brand'] = makeSafe($_REQUEST['brand']);
        if($data['brand'] == empty_lookup_value){ $data['brand'] = ''; }
    $data['status'] = makeSafe($_REQUEST['status']);
        if($data['status'] == empty_lookup_value){ $data['status'] = ''; }
    $data['ico'] = PrepareUploadedFile('ico', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['ico']) createThumbnail($data['ico'], getThumbnailSpecs('products', 'ico', 'tv'));
	if($data['ico']) createThumbnail($data['ico'], getThumbnailSpecs('products', 'ico', 'dv'));

    $data['serial'] = makeSafe($_REQUEST['serial']);
		if($data['serial'] == empty_lookup_value){ $data['serial'] = ''; }
    
    $data['name'] = makeSafe($_REQUEST['name']);
		if($data['name'] == empty_lookup_value){ $data['name'] = ''; }
	if($data['name']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Name': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from products where id='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			if(!$data['ico']) $data['ico'] = makeSafe($row['ico']);
			
		}
	}
	// hook: products_before_insert
	if(function_exists('products_before_insert')){
		$args=array();
		if(!products_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `products` set       `name`=' . (($data['name'] !== '' && $data['name'] !== NULL) ? "'{$data['name']}'" : 'NULL') . ', `cost`=' . (($data['cost'] !== '' && $data['cost'] !== NULL) ? "'{$data['cost']}'" : 'NULL') . ', `weight`=' . (($data['weight'] !== '' && $data['weight'] !== NULL) ? "'{$data['weight']}'" : 'NULL') . ', `quantity`=' . (($data['quantity'] !== '' && $data['quantity'] !== NULL) ? "'{$data['quantity']}'" : 'NULL'). ', `category`=' . (($data['category'] !== '' && $data['category'] !== NULL) ? "'{$data['category']}'" : 'NULL'). ', `brand`=' . (($data['brand'] !== '' && $data['brand'] !== NULL) ? "'{$data['brand']}'" : 'NULL'). ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL'). ', `ico`=' . (($data['ico'] !== '' && $data['ico'] !== NULL) ? "'{$data['ico']}'" : 'NULL'). ', `serial`=' . (($data['serial'] !== '' && $data['serial'] !== NULL) ? "'{$data['serial']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"products_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: products_after_insert
	if(function_exists('products_after_insert')){
		$res = sql("select * from `products` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!products_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('products', $recID, getLoggedMemberID());

	return $recID;
}

function products_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('products');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='products' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='products' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: products_before_delete
	if(function_exists('products_before_delete')){
		$args=array();
		if(!products_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	
	sql("delete from `products` where `id`='$selected_id'", $eo);

	// hook: products_after_delete
	if(function_exists('products_after_delete')){
		$args=array();
		products_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='products' and pkValue='$selected_id'", $eo);
}

function products_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('products');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='products' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='products' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}
    $data['cost'] = makeSafe($_REQUEST['cost']);
        if($data['cost'] == empty_lookup_value){ $data['cost'] = ''; }
    $data['weight'] = makeSafe($_REQUEST['weight']);
        if($data['weight'] == empty_lookup_value){ $data['weight'] = ''; }
    $data['quantity'] = makeSafe($_REQUEST['quantity']);
        if($data['quantity'] == empty_lookup_value){ $data['quantity'] = ''; }
    $data['category'] = makeSafe($_REQUEST['category']);
        if($data['category'] == empty_lookup_value){ $data['category'] = ''; }
    $data['brand'] = makeSafe($_REQUEST['brand']);
        if($data['brand'] == empty_lookup_value){ $data['brand'] = ''; }
    $data['status'] = makeSafe($_REQUEST['status']);
        if($data['status'] == empty_lookup_value){ $data['status'] = ''; }
    if($_REQUEST['ico_remove'] == 1){
		$data['ico'] = '';
	}else{
		$data['ico'] = PrepareUploadedFile('ico', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['ico']) createThumbnail($data['ico'], getThumbnailSpecs('products', 'ico', 'tv'));
		if($data['ico']) createThumbnail($data['ico'], getThumbnailSpecs('products', 'ico', 'dv'));
	}
    $data['serial'] = makeSafe($_REQUEST['serial']);
		if($data['serial'] == empty_lookup_value){ $data['serial'] = ''; }
	$data['name'] = makeSafe($_REQUEST['name']);
		if($data['name'] == empty_lookup_value){ $data['name'] = ''; }

	// alert empty
	if($data['name']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Name': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['cost']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cost': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['weight']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Weight': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['quantity']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Quantity': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['category']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Category': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['brand']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Brand': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['status']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Status': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: products_before_update
	if(function_exists('products_before_update')){
		$args=array();
		if(!products_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `products` set       `name`=' . (($data['name'] !== '' && $data['name'] !== NULL) ? "'{$data['name']}'" : 'NULL') . ', `cost`=' . (($data['cost'] !== '' && $data['cost'] !== NULL) ? "'{$data['cost']}'" : 'NULL') . ', `weight`=' . (($data['weight'] !== '' && $data['weight'] !== NULL) ? "'{$data['weight']}'" : 'NULL') . ', `quantity`=' . (($data['quantity'] !== '' && $data['quantity'] !== NULL) ? "'{$data['quantity']}'" : 'NULL'). ', `category`=' . (($data['category'] !== '' && $data['category'] !== NULL) ? "'{$data['category']}'" : 'NULL'). ', `brand`=' . (($data['brand'] !== '' && $data['brand'] !== NULL) ? "'{$data['brand']}'" : 'NULL'). ', `status`=' . (($data['status'] !== '' && $data['status'] !== NULL) ? "'{$data['status']}'" : 'NULL'). ', `ico`=' . (($data['ico'] !== '' && $data['ico'] !== NULL) ? "'{$data['ico']}'" : 'NULL'). ', `serial`=' . (($data['serial'] !== '' && $data['serial'] !== NULL) ? "'{$data['serial']}'" : 'NULL'). " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="products_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: products_after_update
	if(function_exists('products_after_update')){
		$res = sql("SELECT * FROM `products` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!products_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='products' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function products_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('products');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	// combobox: status
	$combo_status = new Combo;
	$combo_status->ListType = 2;
	$combo_status->MultipleSeparator = ', ';
	$combo_status->ListBoxHeight = 10;
	$combo_status->RadiosPerLine = 1;
	$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Active;;Cancelled;;in stock")));
	$combo_status->ListData = $combo_status->ListItem;
	$combo_status->SelectName = 'status';
	$combo_status->AllowNull = false;
	$combo_status->Render();

	ob_start();

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='products' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='products' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `products` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'products_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_status->SelectedData = $row['status'];
	}else{
		$combo_status->SelectedText = ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");

	}

	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/products_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/products_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Pruduct details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return products_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return products_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return products_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ico').replaceWith('<div class=\"form-control-static\" id=\"ico\">' + (jQuery('#ico').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#name').replaceWith('<div class=\"form-control-static\" id=\"name\">' + (jQuery('#name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(status)%%>', $combo_status->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(status)%%>', $combo_status->SelectedData, $templateCode);


	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(ico)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input type="file" name="ico" id="ico">'), $templateCode);
	if($AllowUpdate && $row['ico']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(ico)%%>', '<br><input type="checkbox" name="ico_remove" id="ico_remove" value="1"> <label for="ico_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(ico)%%>', '', $templateCode);
	}

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', safe_html($urow['name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name)%%>', html_attr($row['name']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(cost)%%>', urlencode($urow['cost']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(cost)%%>', safe_html($urow['cost']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cost)%%>', html_attr($row['cost']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(cost)%%>', urlencode($urow['cost']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(weight)%%>', safe_html($urow['weight']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(weight)%%>', html_attr($row['weight']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(weight)%%>', urlencode($urow['weight']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(quantity)%%>', safe_html($urow['quantity']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(quantity)%%>', html_attr($row['quantity']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(quantity)%%>', urlencode($urow['quantity']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', safe_html($urow['category']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', html_attr($row['category']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode($urow['category']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(brand)%%>', safe_html($urow['brand']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(brand)%%>', html_attr($row['brand']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(brand)%%>', urlencode($urow['brand']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
        $templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		$row['ico']=($row['ico']!=''?$row['ico']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(ico)%%>', html_attr($row['ico']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(ico)%%>', urlencode($urow['ico']), $templateCode);
        if( $dvprint) $templateCode = str_replace('<%%VALUE(serial)%%>', safe_html($urow['serial']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(serial)%%>', html_attr($row['serial']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serial)%%>', urlencode($urow['serial']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(name)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(cost)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(cost)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(weight)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(weight)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(quantity)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(quantity)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(category)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(brand)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(brand)%%>', urlencode(''), $templateCode);
        $templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
        $templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(ico)%%>', 'blank.gif', $templateCode);
        $templateCode = str_replace('<%%VALUE(serial)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serial)%%>', urlencode(''), $templateCode);
	}
	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('products');
	if($selected_id){
		$jdata = get_joined_record('products', $selected_id);
		if($jdata === false) $jdata = get_defaults('products');
		$rdata = $row;
	}
	$templateCode .= loadView('products-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: products_dv
	if(function_exists('products_dv')){
		$args=array();
		products_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>